"""Landmark synthesis: pick a replacement landmark for un-groundable subs.

Domain logic for pipeline step 11 (``scripts/11_rescue_blacklist.sh``).
The CLI + per-scan orchestration stays in
``src/check/rescue_blacklist.py``; this module owns:

  * source collection — which (ep, sub) cells need a replacement
    (blacklist drops / detection failures / visibility misses)
  * the referrability table (MPCat40 category → tier)
  * candidate ranking — voxel-visibility / approach / tier filters and
    the ``approach × size_weight`` score
  * label resolution — ``fine`` categories name themselves; ``collective``
    ones go through the VLM (with an on-disk per-instance cache)
  * the synthesized sub-instruction template

Selection algorithm (per candidate sub-path):

  1. Render an RGB + depth + semantic equirectangular panorama at BOTH
     the partition pose and the end pose; unproject + voxelise via
     :mod:`src.env.geometry`.
  2. Visibility filter — require
     ``partition_voxels[iid] / end_voxels[iid] >= MIN_VISIBILITY_RATIO``.
  3. Approach filter — require ``dist_partition > dist_end``.
  4. Tier filter — drop ``too_generic`` categories.
  5. Sort survivors by descending ``approach × size_weight`` and walk
     them in order: ``fine`` → commit the MPCat40 token; ``collective``
     → ask the VLM, accept on high confidence, else fall through.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Callable, Dict, List, Optional, Tuple

import numpy as np
import yaml

from src.pipeline.audit import detection_rescued
from src.process.vlm_common import extract_json_object_lenient, image_data_url

# Path to the 3-tier MPCat40 classification (regenerated by
# scripts/build_landmark_referrable.sh). Categories absent from this
# file default to ``fine``.
REFERRABLE_TABLE_PATH = (
    Path(__file__).resolve().parents[2] / "configs" / "landmark_referrable.yaml"
)

# A candidate landmark must be at least this fraction as visible at
# the partition pose as it is at the end pose. The intuition: when the
# agent reads "walk to a X", they must already be able to see X
# clearly enough — a destination that's invisible from where the
# instruction is read isn't a usable landmark. 0.10 means "at least
# 10% of the eventual voxel coverage is already on screen at
# instruction-read time."
MIN_VISIBILITY_RATIO = 0.10

# Score saturation point on partition-pose voxel count. Above this the
# soft-size penalty contributes ``1.0``; below it the candidate's score
# is linearly discounted. 200 voxels at 0.10 m ≈ a 0.5-m-cube object's
# visible surface — the smallest area we still treat as "clearly
# visible". Below that an instance is small enough that a huge approach
# distance no longer means it's a confident destination.
SIZE_SATURATION_VOXELS = 200

# Confidence values from the VLM that count as "accept and use the
# refined name". Anything else falls through to the next candidate.
_VLM_ACCEPT_CONFIDENCES = {"high"}


def _load_yaml(path: Path) -> dict:
    if not path.exists():
        return {}
    with open(path) as f:
        return yaml.safe_load(f) or {}


# ── Referrability table ──────────────────────────────────────────────────
def load_referrability_table() -> Dict[str, str]:
    """Read ``configs/landmark_referrable.yaml`` → ``{category: tier}``.

    Returns an empty dict if the file is missing — every category will
    then default to ``fine`` (the old behaviour minus the structural
    blacklist), so the pipeline still runs but with no smart filtering.
    Print a warning in that case so the user knows to regenerate.
    """
    payload = _load_yaml(REFERRABLE_TABLE_PATH)
    cats = (payload or {}).get("categories") or {}
    if not cats:
        print(
            f"  WARN [referrability table] no entries at {REFERRABLE_TABLE_PATH}; "
            "every MPCat40 category will default to 'fine'. Regenerate via "
            "scripts/build_landmark_referrable.sh."
        )
    return {str(k).strip().lower(): str(v).strip().lower() for k, v in cats.items()}


def _tier(referrability: Dict[str, str], cat: str) -> str:
    """Look up the tier for an MPCat40 category, defaulting to ``fine``."""
    key = (cat or "").strip().lower()
    return referrability.get(key, "fine")


# ── VLM instance naming (used for `collective` tier) ─────────────────────
_VLM_NAMING_SYSTEM = """\
You identify the highlighted object in an indoor scene panorama so it
can be used as a navigation landmark in a synthesized instruction of
the form "... walk to a X.".

Return JSON only (no markdown):

  {"name": "<short noun phrase, 1-3 words>",
   "confidence": "high" | "low",
   "reason": "<one short sentence>"}

Rules:
  - confidence=high ONLY when you can clearly identify the object.
  - The name must read naturally in "walk to a <name>" — prefer
    concrete everyday English ("refrigerator", "office chair",
    "ceiling lamp"). Do NOT return the bucket name verbatim
    ("appliance", "furniture", "lighting") — those are too generic;
    set confidence=low if you can't be more specific.
  - If the highlighted object is unclear, occluded, or you would only
    be guessing, set confidence=low.
"""


def name_instance_via_vlm(
    client,
    *,
    model: str,
    image_path: Path,
    coarse_category: str,
    max_retries: int = 2,
    temperature: float = 0.0,
    max_tokens: int = 256,
) -> Dict:
    """Ask the VLM what the highlighted instance is.

    Returns a dict with ``name`` / ``confidence`` / ``reason`` keys
    (possibly empty strings on parse failure or transport error).
    """
    user_text = (
        f"The highlighted region shows a single instance whose coarse "
        f"MPCat40 category is '{coarse_category}'. Identify the object "
        f"more specifically."
    )
    content = [
        {"type": "text",      "text": user_text},
        {"type": "image_url", "image_url": {"url": image_data_url(image_path)}},
    ]
    last_err: Optional[Exception] = None
    for attempt in range(1, max_retries + 1):
        try:
            try:
                resp = client.chat.completions.create(
                    model=model,
                    temperature=temperature,
                    max_tokens=max_tokens,
                    response_format={"type": "json_object"},
                    messages=[
                        {"role": "system", "content": _VLM_NAMING_SYSTEM},
                        {"role": "user",   "content": content},
                    ],
                )
            except TypeError:
                # Older clients without response_format support.
                resp = client.chat.completions.create(
                    model=model,
                    temperature=temperature,
                    max_tokens=max_tokens,
                    messages=[
                        {"role": "system", "content": _VLM_NAMING_SYSTEM},
                        {"role": "user",   "content": content},
                    ],
                )
            raw = (resp.choices[0].message.content or "").strip()
            parsed = extract_json_object_lenient(raw)
            name = (parsed.get("name") or "").strip()
            conf = (parsed.get("confidence") or "").strip().lower()
            return {
                "name":       name,
                "confidence": conf,
                "reason":     (parsed.get("reason") or "").strip(),
                "raw":        raw,
                "model":      model,
            }
        except Exception as exc:
            last_err = exc
    return {"name": "", "confidence": "low",
            "reason": f"vlm error: {last_err}", "raw": "", "model": model}


def load_vlm_cache(scan_dir: Path) -> Dict[str, Dict]:
    p = scan_dir / "vlm_instance_labels.json"
    if not p.exists():
        return {}
    try:
        with open(p) as f:
            data = json.load(f) or {}
    except json.JSONDecodeError:
        return {}
    return data.get("labels") or {}


def save_vlm_cache(scan_dir: Path, scan: str, labels: Dict[str, Dict]) -> None:
    if not labels:
        return
    scan_dir.mkdir(parents=True, exist_ok=True)
    p = scan_dir / "vlm_instance_labels.json"
    with open(p, "w") as f:
        json.dump({"scan": scan, "labels": labels}, f, indent=2, ensure_ascii=False)


# ── Synthesis-source collection ──────────────────────────────────────────
def blacklist_drops(filt_dir: Path) -> List[Tuple[int, int, Dict]]:
    """Return ``[(ep_id, sub_idx, drop_record), ...]`` from
    ``02_blacklist_dropped.yaml``.

    Each ``drop_record`` carries ``landmark`` + ``reason`` + ``origin =
    "blacklist"`` so the synthesis loop can treat blacklist drops and
    detection failures uniformly downstream.
    """
    payload = _load_yaml(filt_dir / "02_blacklist_dropped.yaml")
    out: List[Tuple[int, int, Dict]] = []
    for ep_id_str, info in (payload.get("dropped") or {}).items():
        for sub_idx_str, rec in ((info or {}).get("subs") or {}).items():
            try:
                out.append((
                    int(ep_id_str),
                    int(sub_idx_str),
                    {**(rec or {}), "origin": "blacklist"},
                ))
            except ValueError:
                continue
    return out


def detection_failures(audit: dict) -> List[Tuple[int, int, Dict]]:
    """Return ``[(ep_id, sub_idx, drop_record), ...]`` for every sub where
    stage 09 (detection) emitted a ``rescue_failed`` event.

    Same shape as :func:`blacklist_drops` so they can be merged into one
    candidate list. The original landmark and YOLO failure reason come
    from the event payload (stage 09 records both); ``origin`` is set to
    ``"detection_failure"`` so the synthesis output can distinguish the
    two sources.
    """
    out: List[Tuple[int, int, Dict]] = []
    for ep_id_str, ep in (audit.get("episodes") or {}).items():
        for sub_idx_str, sp in (ep.get("sub_paths") or {}).items():
            failed = [
                e for e in (sp.get("events") or [])
                if e.get("stage") == "detection"
                and e.get("action") == "rescue_failed"
            ]
            if not failed:
                continue
            last = failed[-1]
            try:
                ep_id = int(ep_id_str)
                sub_idx = int(sub_idx_str)
            except ValueError:
                continue
            out.append((ep_id, sub_idx, {
                "landmark": last.get("landmark") or "",
                "reason":   f"detection:{last.get('reason') or 'unknown'}",
                "origin":   "detection_failure",
            }))
    return out


def visibility_not_visible_failures(audit: dict) -> List[Tuple[int, int, Dict]]:
    """Return ``[(ep_id, sub_idx, drop_record), ...]`` for every sub where
    stage 07 (visibility) labeled the original landmark ``not_visible``.

    These are the "fine MPCat40 match but no instance visible at the
    partition pose" cases — the landmark text is conceptually fine
    (e.g. ``bath`` → ``bathtub``) but no bathtub is on screen when the
    agent reads the instruction. Step 09 skips them because they have a
    fine match (not coarse-only or no_match), and the blacklist channel
    doesn't catch them either, so without an extra rescue path they
    ended up in dataset.json with empty ``target_instance_ids`` —
    technically included but practically unusable.

    Same shape as :func:`blacklist_drops`; ``origin`` is set to
    ``"visibility_not_visible"``. Step 12 (consolidate) excludes the
    original records of these subs from the dataset, so when no synth
    succeeds the sub is left out (dataset only contains records whose
    landmark is actually visible at the partition pose).
    """
    out: List[Tuple[int, int, Dict]] = []
    for ep_id_str, ep in (audit.get("episodes") or {}).items():
        for sub_idx_str, sp in (ep.get("sub_paths") or {}).items():
            events = sp.get("events") or []
            labeled = [
                e for e in events
                if e.get("stage") == "visibility"
                and e.get("action") == "labeled"
                and e.get("visibility") == "not_visible"
            ]
            if not labeled:
                continue
            # Step 09 may have grounded the original landmark after the
            # visibility label (semantic sensor missed it, detector found
            # it). The rescued original is usable as-is — synthesizing a
            # replacement on top would put the same (ep, sub) into
            # dataset.json twice.
            if detection_rescued(events):
                continue
            last = labeled[-1]
            try:
                ep_id = int(ep_id_str)
                sub_idx = int(sub_idx_str)
            except ValueError:
                continue
            out.append((ep_id, sub_idx, {
                "landmark": last.get("landmark") or "",
                "reason":   "visibility:not_visible",
                "origin":   "visibility_not_visible",
            }))
    return out


def merge_drops(
    *sources: List[Tuple[int, int, Dict]],
) -> List[Tuple[int, int, Dict]]:
    """Concatenate drop lists and keep the first occurrence per (ep, sub).

    Blacklist drops take precedence over detection failures (we list them
    first at the call site), since a blacklisted sub never reaches step
    09 — but guarding anyway in case the upstream order changes.
    """
    seen: set = set()
    merged: List[Tuple[int, int, Dict]] = []
    for source in sources:
        for ep, sub, rec in source:
            key = (ep, sub)
            if key in seen:
                continue
            seen.add(key)
            merged.append((ep, sub, rec))
    return merged


# ── Pose / node helpers ──────────────────────────────────────────────────
def resolve_node_pos(
    node_id: str, virtual_nodes: Dict[str, List[float]], scan_db: Dict[str, np.ndarray],
) -> Optional[np.ndarray]:
    if isinstance(node_id, str) and node_id.startswith("virt:"):
        pos = virtual_nodes.get(node_id)
        return np.asarray(pos, dtype=np.float32) if pos is not None else None
    if node_id in scan_db:
        return np.asarray(scan_db[node_id], dtype=np.float32)
    return None


# ── Candidate scoring / ranking ──────────────────────────────────────────
def _size_weight(partition_voxels: int) -> float:
    """Soft penalty for spatially-small instances at the partition pose.

    Returns a multiplier in ``[0, 1]`` that saturates at
    ``SIZE_SATURATION_VOXELS``. A 5-voxel speck gets weight 0.025, a
    200+ voxel landmark gets weight 1.0. Multiplied into the candidate
    score so a huge approach distance no longer compensates for a
    barely-visible destination.
    """
    return min(1.0, max(0.0, partition_voxels) / float(SIZE_SATURATION_VOXELS))


def _candidate_score(c: Dict) -> float:
    """Selection score for one candidate.

    ``approach × size_weight``. Maximised to pick the best landmark:
    we still want the instance the agent walks toward the most, but
    that signal is muted when the instance occupies few voxels at the
    instruction-read pose (i.e. is spatially small from there).
    """
    return c["approach_m"] * _size_weight(c["voxel_count"])


def rank_candidates(
    partition_voxels: Dict[int, int],
    end_voxels:       Dict[int, int],
    inst_meta:        Dict[int, Dict],
    partition_pos:    np.ndarray,
    end_pos:          np.ndarray,
    referrability:    Dict[str, str],
    debug_prefix:     str = "",
) -> List[Dict]:
    """Geometric-filter all instances and return candidates sorted by
    descending score.

    Per-candidate filters (all must pass):
      1. instance has a known MPCat40 category
      2. ratio = partition_voxels / end_voxels >= MIN_VISIBILITY_RATIO
      3. dist_partition > dist_end (agent walks toward the instance)
      4. tier(cat) != "too_generic"

    Survivors are ranked by ``score = approach_m × size_weight``, where
    ``size_weight`` saturates at ``SIZE_SATURATION_VOXELS`` so tiny
    instances can't ride a long approach to the top of the list.

    No VLM is called here — that happens at pick time in
    :func:`pick_replacement_landmark`, only for the candidate(s) we
    actually want to commit to.
    """
    candidates: List[Dict] = []
    all_iids = set(partition_voxels) | set(end_voxels)

    print(f"{debug_prefix}  end-pose visible instances (top 10 by voxel count):")
    top = sorted(end_voxels.items(), key=lambda kv: -kv[1])[:10]
    for iid, end_vx in top:
        meta = inst_meta.get(iid) or {}
        cat = meta.get("category") or "?"
        p_vx = partition_voxels.get(iid, 0)
        ratio = (p_vx / end_vx) if end_vx > 0 else 0.0
        center = meta.get("center")
        if center is not None:
            dist_p = float(np.linalg.norm(partition_pos - center))
            dist_e = float(np.linalg.norm(end_pos - center))
            print(f"{debug_prefix}    iid={iid:>4} cat={cat:<14s} tier={_tier(referrability, cat):<11s} "
                  f"e_vx={end_vx:>5d} p_vx={p_vx:>5d} ratio={ratio:.2f} "
                  f"approach={dist_p-dist_e:+.2f}m")
        else:
            print(f"{debug_prefix}    iid={iid:>4} cat={cat:<14s} "
                  f"e_vx={end_vx:>5d} p_vx={p_vx:>5d} ratio={ratio:.2f} "
                  f"(no .house center)")

    for iid in all_iids:
        if iid not in inst_meta:
            continue
        cat = inst_meta[iid]["category"]
        if not cat:
            continue
        tier = _tier(referrability, cat)
        if tier == "too_generic":
            continue
        end_vx = end_voxels.get(iid, 0)
        if end_vx <= 0:
            continue
        p_vx = partition_voxels.get(iid, 0)
        ratio = p_vx / end_vx
        if ratio < MIN_VISIBILITY_RATIO:
            continue
        center = inst_meta[iid]["center"]
        dist_p = float(np.linalg.norm(partition_pos - center))
        dist_e = float(np.linalg.norm(end_pos - center))
        approach = dist_p - dist_e
        if approach <= 0:
            continue
        candidates.append({
            "instance_id":      iid,
            "category":         cat,
            "tier":             tier,
            "voxel_count":      p_vx,
            "voxels_at_end":    end_vx,
            "ratio":            ratio,
            "dist_partition_m": dist_p,
            "dist_end_m":       dist_e,
            "approach_m":       approach,
        })

    if not candidates:
        print(f"{debug_prefix}  → no fit candidate "
              f"(too_generic, ratio < {MIN_VISIBILITY_RATIO:.2f}, or not approaching)")
        return []

    # Sort by descending score (approach × size_weight). Tie-break on
    # raw partition voxel count so a spatially-clear candidate beats an
    # equally-scored barely-visible one.
    for c in candidates:
        c["score"] = _candidate_score(c)
    candidates.sort(key=lambda c: (-c["score"], -c["voxel_count"]))
    print(f"{debug_prefix}  candidates ranked by score "
          f"(approach × min(1, p_vx/{SIZE_SATURATION_VOXELS})) — {len(candidates)} total:")
    for c in candidates:
        print(f"{debug_prefix}    iid={c['instance_id']:>4} cat={c['category']:<14s} "
              f"tier={c['tier']:<11s} p_vx={c['voxel_count']:>5d} e_vx={c['voxels_at_end']:>5d} "
              f"ratio={c['ratio']:.2f} approach={c['approach_m']:+.2f}m "
              f"score={c['score']:+.2f}")
    return candidates


def resolve_label(
    candidate:   Dict,
    *,
    partition_pos:    np.ndarray,
    scan:        str,
    ep_id:       int,
    sub_idx:     int,
    sub_total:   int,
    checker,
    vlm_client,
    vlm_model:   str,
    vlm_cache:   Dict[str, Dict],
    viz_dir:     Path,
    render_mask_fn: Callable,
    debug_prefix: str = "",
) -> Optional[Dict]:
    """Decide the human-facing landmark name for one candidate.

    Returns ``None`` if the candidate must be skipped (collective + no
    VLM available, or collective + VLM unable to identify). Otherwise
    returns ``{"name": ..., "source": "mpcat40" | "vlm", "vlm": ...}``.

    ``render_mask_fn`` renders the instance-highlight PNG the VLM looks
    at (injected by the caller so this module doesn't depend on the
    viz/CLI layer); it must accept the keyword arguments
    ``checker, scan, instance_id, frame_record, out_path, info_width``.

    Per-instance VLM responses are cached in ``vlm_cache`` and persist
    across runs at ``target_instances/<scan>/vlm_instance_labels.json``,
    so calling this function many times for the same instance pays the
    VLM cost only once.
    """
    cat = candidate["category"]
    tier = candidate["tier"]
    if tier == "fine":
        return {"name": cat, "source": "mpcat40", "vlm": None}
    if tier != "collective":
        return None  # too_generic — shouldn't reach here, but be safe.

    if vlm_client is None:
        print(f"{debug_prefix}    iid={candidate['instance_id']} "
              f"collective(cat={cat!r}) — VLM disabled, skipping")
        return None

    cache_key = str(candidate["instance_id"])
    cached = vlm_cache.get(cache_key)
    if cached and cached.get("name") is not None:
        result = cached
        print(f"{debug_prefix}    iid={candidate['instance_id']} cat={cat!r} "
              f"(VLM cache) → name={result.get('name')!r} "
              f"conf={result.get('confidence')!r}")
    else:
        # Render the highlighted instance at the partition pose so the
        # VLM sees what the agent sees when reading the instruction.
        mask_path = viz_dir / f"sub_{sub_idx:03d}_iid_{candidate['instance_id']}_vlm.png"
        try:
            render_mask_fn(
                checker=checker,
                scan=scan,
                instance_id=int(candidate["instance_id"]),
                frame_record={
                    "position":       [float(x) for x in partition_pos],
                    "heading":        0.0,
                    "instruction_id": ep_id,
                    "instruction":    f"identify the highlighted {cat}",
                    "landmark":       cat,
                    "sub_idx":        sub_idx,
                    "sub_total":      sub_total,
                    "step":           0,
                    "action":         "VLM_NAMING",
                },
                out_path=mask_path,
                info_width=300,
            )
        except Exception as exc:
            print(f"{debug_prefix}    iid={candidate['instance_id']} "
                  f"mask render failed: {exc}; skipping")
            return None

        result = name_instance_via_vlm(
            client=vlm_client,
            model=vlm_model,
            image_path=mask_path,
            coarse_category=cat,
        )
        # Persist into the cache regardless of confidence — repeated
        # uncertainty is a real signal we want to remember.
        vlm_cache[cache_key] = {
            "instance_id":     int(candidate["instance_id"]),
            "coarse_category": cat,
            "name":            result.get("name") or "",
            "confidence":      result.get("confidence") or "",
            "reason":          result.get("reason") or "",
            "model":           result.get("model") or vlm_model,
            "mask_path":       str(mask_path),
        }
        print(f"{debug_prefix}    iid={candidate['instance_id']} cat={cat!r} "
              f"→ VLM name={result.get('name')!r} conf={result.get('confidence')!r}")

    name = (result.get("name") or "").strip()
    conf = (result.get("confidence") or "").strip().lower()
    bucket_norm = cat.strip().lower()
    if (conf in _VLM_ACCEPT_CONFIDENCES
            and name
            and name.strip().lower() != bucket_norm):
        return {
            "name":   name,
            "source": "vlm",
            "vlm":    {
                "confidence": conf,
                "model":      result.get("model"),
                "reason":     result.get("reason"),
            },
        }
    return None


def pick_replacement_landmark(
    partition_voxels: Dict[int, int],
    end_voxels:       Dict[int, int],
    inst_meta:        Dict[int, Dict],
    partition_pos:    np.ndarray,
    end_pos:          np.ndarray,
    referrability:    Dict[str, str],
    *,
    scan:        str,
    ep_id:       int,
    sub_idx:     int,
    sub_total:   int,
    checker,
    vlm_client,
    vlm_model:   str,
    vlm_cache:   Dict[str, Dict],
    viz_dir:     Path,
    render_mask_fn: Callable,
    debug_prefix: str = "",
) -> Optional[Dict]:
    """Pick one replacement landmark or return ``None``.

    Two-stage selection:

      1. :func:`rank_candidates` filters every visible instance by
         visibility ratio (>= 10%), approach (> 0), and tier
         (drops ``too_generic``), then sorts the survivors by max
         approach.
      2. Walk the sorted list in order. For each candidate,
         :func:`resolve_label` decides what to call it:
             - ``fine``       → use the MPCat40 token directly,
             - ``collective`` → render a mask, ask the VLM; accept the
                                VLM's specific name if it's confident,
                                else fall through to the next candidate.
      Return the first candidate that yields a usable label.
    """
    candidates = rank_candidates(
        partition_voxels=partition_voxels,
        end_voxels=end_voxels,
        inst_meta=inst_meta,
        partition_pos=partition_pos,
        end_pos=end_pos,
        referrability=referrability,
        debug_prefix=debug_prefix,
    )
    if not candidates:
        return None

    for c in candidates:
        label = resolve_label(
            c,
            partition_pos=partition_pos,
            scan=scan, ep_id=ep_id, sub_idx=sub_idx, sub_total=sub_total,
            checker=checker,
            vlm_client=vlm_client, vlm_model=vlm_model,
            vlm_cache=vlm_cache, viz_dir=viz_dir,
            render_mask_fn=render_mask_fn,
            debug_prefix=debug_prefix,
        )
        if label is None:
            continue
        chosen = dict(c)
        chosen["new_landmark"]        = label["name"]
        chosen["new_landmark_source"] = label["source"]
        chosen["vlm"]                 = label["vlm"]

        # Informational: how many instances of the chosen MPCat40
        # category are visible at the partition pose? Tells downstream
        # consumers whether the synthesized landmark is ambiguous.
        cat_in_partition_fov = sum(
            1 for iid, vx in partition_voxels.items()
            if vx > 0 and inst_meta.get(iid, {}).get("category") == chosen["category"]
        )
        chosen["fov_instance_count"] = cat_in_partition_fov
        chosen["unique_in_fov"]      = cat_in_partition_fov == 1
        print(f"{debug_prefix}  → picked iid={chosen['instance_id']} "
              f"name={chosen['new_landmark']!r} "
              f"(source={chosen['new_landmark_source']}, "
              f"cat={chosen['category']!r}, "
              f"approach={chosen['approach_m']:+.2f}m, "
              f"score={chosen.get('score', 0.0):+.2f})")
        return chosen

    print(f"{debug_prefix}  → no candidate produced a usable label "
          "(all collective candidates were VLM-uncertain)")
    return None


def synth_sub_instruction(spatial: str, landmark_category: str) -> str:
    spatial = (spatial or "").strip().rstrip(".")
    article = "an" if landmark_category[:1] in "aeiou" else "a"
    if spatial:
        return f"{spatial}. Walk to {article} {landmark_category}."
    return f"Walk to {article} {landmark_category}."
